# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/order/product_inquiry_reply/product_inquiry_reply.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/order/product_inquiry_reply/product_inquiry_reply.proto',
  package='productinquiryreply',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n>protos/order/product_inquiry_reply/product_inquiry_reply.proto\x12\x13productinquiryreply\"\xae\x01\n\x13ProductInquiryReply\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04\x62ody\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\t\x12\x17\n\ndeleted_at\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x17\n\x0fproduct_inquiry\x18\x05 \x01(\x03\x12\x15\n\ruser_username\x18\x06 \x01(\t\x12\x11\n\tuser_uuid\x18\x07 \x01(\tB\r\n\x0b_deleted_atb\x06proto3'
)




_PRODUCTINQUIRYREPLY = _descriptor.Descriptor(
  name='ProductInquiryReply',
  full_name='productinquiryreply.ProductInquiryReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='productinquiryreply.ProductInquiryReply.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='body', full_name='productinquiryreply.ProductInquiryReply.body', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='productinquiryreply.ProductInquiryReply.created_at', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deleted_at', full_name='productinquiryreply.ProductInquiryReply.deleted_at', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='product_inquiry', full_name='productinquiryreply.ProductInquiryReply.product_inquiry', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_username', full_name='productinquiryreply.ProductInquiryReply.user_username', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_uuid', full_name='productinquiryreply.ProductInquiryReply.user_uuid', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_deleted_at', full_name='productinquiryreply.ProductInquiryReply._deleted_at',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=88,
  serialized_end=262,
)

_PRODUCTINQUIRYREPLY.oneofs_by_name['_deleted_at'].fields.append(
  _PRODUCTINQUIRYREPLY.fields_by_name['deleted_at'])
_PRODUCTINQUIRYREPLY.fields_by_name['deleted_at'].containing_oneof = _PRODUCTINQUIRYREPLY.oneofs_by_name['_deleted_at']
DESCRIPTOR.message_types_by_name['ProductInquiryReply'] = _PRODUCTINQUIRYREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProductInquiryReply = _reflection.GeneratedProtocolMessageType('ProductInquiryReply', (_message.Message,), {
  'DESCRIPTOR' : _PRODUCTINQUIRYREPLY,
  '__module__' : 'protos.order.product_inquiry_reply.product_inquiry_reply_pb2'
  # @@protoc_insertion_point(class_scope:productinquiryreply.ProductInquiryReply)
  })
_sym_db.RegisterMessage(ProductInquiryReply)


# @@protoc_insertion_point(module_scope)
