# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/logistics/package_log/package_log.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/logistics/package_log/package_log.proto',
  package='package_log',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n.protos/logistics/package_log/package_log.proto\x12\x0bpackage_log\x1a\x1bgoogle/protobuf/empty.proto\"\x99\x01\n\nPackageLog\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\t\x12\x12\n\nfield_name\x18\x04 \x01(\t\x12\x0e\n\x06\x62\x65\x66ore\x18\x05 \x01(\t\x12\r\n\x05\x61\x66ter\x18\x06 \x01(\t\x12\x12\n\ncreated_by\x18\x07 \x01(\x05\x12\x0f\n\x07package\x18\x08 \x01(\x03\"\x17\n\x15PackageLogListRequest\"\'\n\x19PackageLogRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xe8\x02\n\x14PackageLogController\x12G\n\x04List\x12\".package_log.PackageLogListRequest\x1a\x17.package_log.PackageLog\"\x00\x30\x01\x12<\n\x06\x43reate\x12\x17.package_log.PackageLog\x1a\x17.package_log.PackageLog\"\x00\x12M\n\x08Retrieve\x12&.package_log.PackageLogRetrieveRequest\x1a\x17.package_log.PackageLog\"\x00\x12<\n\x06Update\x12\x17.package_log.PackageLog\x1a\x17.package_log.PackageLog\"\x00\x12<\n\x07\x44\x65stroy\x12\x17.package_log.PackageLog\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_PACKAGELOG = _descriptor.Descriptor(
  name='PackageLog',
  full_name='package_log.PackageLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='package_log.PackageLog.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='package_log.PackageLog.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='created_at', full_name='package_log.PackageLog.created_at', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='field_name', full_name='package_log.PackageLog.field_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='before', full_name='package_log.PackageLog.before', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='after', full_name='package_log.PackageLog.after', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='created_by', full_name='package_log.PackageLog.created_by', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='package', full_name='package_log.PackageLog.package', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=246,
)


_PACKAGELOGLISTREQUEST = _descriptor.Descriptor(
  name='PackageLogListRequest',
  full_name='package_log.PackageLogListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=271,
)


_PACKAGELOGRETRIEVEREQUEST = _descriptor.Descriptor(
  name='PackageLogRetrieveRequest',
  full_name='package_log.PackageLogRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='package_log.PackageLogRetrieveRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=273,
  serialized_end=312,
)

DESCRIPTOR.message_types_by_name['PackageLog'] = _PACKAGELOG
DESCRIPTOR.message_types_by_name['PackageLogListRequest'] = _PACKAGELOGLISTREQUEST
DESCRIPTOR.message_types_by_name['PackageLogRetrieveRequest'] = _PACKAGELOGRETRIEVEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PackageLog = _reflection.GeneratedProtocolMessageType('PackageLog', (_message.Message,), {
  'DESCRIPTOR' : _PACKAGELOG,
  '__module__' : 'protos.logistics.package_log.package_log_pb2'
  # @@protoc_insertion_point(class_scope:package_log.PackageLog)
  })
_sym_db.RegisterMessage(PackageLog)

PackageLogListRequest = _reflection.GeneratedProtocolMessageType('PackageLogListRequest', (_message.Message,), {
  'DESCRIPTOR' : _PACKAGELOGLISTREQUEST,
  '__module__' : 'protos.logistics.package_log.package_log_pb2'
  # @@protoc_insertion_point(class_scope:package_log.PackageLogListRequest)
  })
_sym_db.RegisterMessage(PackageLogListRequest)

PackageLogRetrieveRequest = _reflection.GeneratedProtocolMessageType('PackageLogRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _PACKAGELOGRETRIEVEREQUEST,
  '__module__' : 'protos.logistics.package_log.package_log_pb2'
  # @@protoc_insertion_point(class_scope:package_log.PackageLogRetrieveRequest)
  })
_sym_db.RegisterMessage(PackageLogRetrieveRequest)



_PACKAGELOGCONTROLLER = _descriptor.ServiceDescriptor(
  name='PackageLogController',
  full_name='package_log.PackageLogController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=315,
  serialized_end=675,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='package_log.PackageLogController.List',
    index=0,
    containing_service=None,
    input_type=_PACKAGELOGLISTREQUEST,
    output_type=_PACKAGELOG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='package_log.PackageLogController.Create',
    index=1,
    containing_service=None,
    input_type=_PACKAGELOG,
    output_type=_PACKAGELOG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Retrieve',
    full_name='package_log.PackageLogController.Retrieve',
    index=2,
    containing_service=None,
    input_type=_PACKAGELOGRETRIEVEREQUEST,
    output_type=_PACKAGELOG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='package_log.PackageLogController.Update',
    index=3,
    containing_service=None,
    input_type=_PACKAGELOG,
    output_type=_PACKAGELOG,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Destroy',
    full_name='package_log.PackageLogController.Destroy',
    index=4,
    containing_service=None,
    input_type=_PACKAGELOG,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PACKAGELOGCONTROLLER)

DESCRIPTOR.services_by_name['PackageLogController'] = _PACKAGELOGCONTROLLER

# @@protoc_insertion_point(module_scope)
