# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/logistics/shipping_candidate/shipping_candidate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos.logistics.inventory import inventory_pb2 as protos_dot_logistics_dot_inventory_dot_inventory__pb2
from protos.order.order_item import order_item_pb2 as protos_dot_order_dot_order__item_dot_order__item__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/logistics/shipping_candidate/shipping_candidate.proto',
  package='shippingcandidate',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n<protos/logistics/shipping_candidate/shipping_candidate.proto\x12\x11shippingcandidate\x1a*protos/logistics/inventory/inventory.proto\x1a(protos/order/order_item/order_item.proto\"x\n\x11ShippingCandidate\x12\"\n\x04item\x18\x01 \x01(\x0b\x32\x14.orderitem.OrderItem\x12)\n\x0binventories\x18\x02 \x03(\x0b\x32\x14.inventory.Inventory\x12\x14\n\x0cis_fulfilled\x18\x03 \x01(\x08\x62\x06proto3'
  ,
  dependencies=[protos_dot_logistics_dot_inventory_dot_inventory__pb2.DESCRIPTOR,protos_dot_order_dot_order__item_dot_order__item__pb2.DESCRIPTOR,])




_SHIPPINGCANDIDATE = _descriptor.Descriptor(
  name='ShippingCandidate',
  full_name='shippingcandidate.ShippingCandidate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='shippingcandidate.ShippingCandidate.item', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='inventories', full_name='shippingcandidate.ShippingCandidate.inventories', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_fulfilled', full_name='shippingcandidate.ShippingCandidate.is_fulfilled', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=169,
  serialized_end=289,
)

_SHIPPINGCANDIDATE.fields_by_name['item'].message_type = protos_dot_order_dot_order__item_dot_order__item__pb2._ORDERITEM
_SHIPPINGCANDIDATE.fields_by_name['inventories'].message_type = protos_dot_logistics_dot_inventory_dot_inventory__pb2._INVENTORY
DESCRIPTOR.message_types_by_name['ShippingCandidate'] = _SHIPPINGCANDIDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ShippingCandidate = _reflection.GeneratedProtocolMessageType('ShippingCandidate', (_message.Message,), {
  'DESCRIPTOR' : _SHIPPINGCANDIDATE,
  '__module__' : 'protos.logistics.shipping_candidate.shipping_candidate_pb2'
  # @@protoc_insertion_point(class_scope:shippingcandidate.ShippingCandidate)
  })
_sym_db.RegisterMessage(ShippingCandidate)


# @@protoc_insertion_point(module_scope)
