# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: logistics/protos/courier_proto/courier.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='logistics/protos/courier_proto/courier.proto',
  package='courier',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n,logistics/protos/courier_proto/courier.proto\x12\x07\x63ourier\x1a\x1bgoogle/protobuf/empty.proto\"W\n\x07\x43ourier\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x17\n\x0fsweettracker_id\x18\x03 \x01(\t\x12\x19\n\x11tracking_url_base\x18\x04 \x01(\t\"\x14\n\x12\x43ourierListRequest\"$\n\x16\x43ourierRetrieveRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x32\xa6\x02\n\x11\x43ourierController\x12\x39\n\x04List\x12\x1b.courier.CourierListRequest\x1a\x10.courier.Courier\"\x00\x30\x01\x12.\n\x06\x43reate\x12\x10.courier.Courier\x1a\x10.courier.Courier\"\x00\x12?\n\x08Retrieve\x12\x1f.courier.CourierRetrieveRequest\x1a\x10.courier.Courier\"\x00\x12.\n\x06Update\x12\x10.courier.Courier\x1a\x10.courier.Courier\"\x00\x12\x35\n\x07\x44\x65stroy\x12\x10.courier.Courier\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_COURIER = _descriptor.Descriptor(
  name='Courier',
  full_name='courier.Courier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='courier.Courier.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='courier.Courier.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sweettracker_id', full_name='courier.Courier.sweettracker_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tracking_url_base', full_name='courier.Courier.tracking_url_base', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=173,
)


_COURIERLISTREQUEST = _descriptor.Descriptor(
  name='CourierListRequest',
  full_name='courier.CourierListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=195,
)


_COURIERRETRIEVEREQUEST = _descriptor.Descriptor(
  name='CourierRetrieveRequest',
  full_name='courier.CourierRetrieveRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='courier.CourierRetrieveRequest.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=233,
)

DESCRIPTOR.message_types_by_name['Courier'] = _COURIER
DESCRIPTOR.message_types_by_name['CourierListRequest'] = _COURIERLISTREQUEST
DESCRIPTOR.message_types_by_name['CourierRetrieveRequest'] = _COURIERRETRIEVEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Courier = _reflection.GeneratedProtocolMessageType('Courier', (_message.Message,), {
  'DESCRIPTOR' : _COURIER,
  '__module__' : 'logistics.protos.courier_proto.courier_pb2'
  # @@protoc_insertion_point(class_scope:courier.Courier)
  })
_sym_db.RegisterMessage(Courier)

CourierListRequest = _reflection.GeneratedProtocolMessageType('CourierListRequest', (_message.Message,), {
  'DESCRIPTOR' : _COURIERLISTREQUEST,
  '__module__' : 'logistics.protos.courier_proto.courier_pb2'
  # @@protoc_insertion_point(class_scope:courier.CourierListRequest)
  })
_sym_db.RegisterMessage(CourierListRequest)

CourierRetrieveRequest = _reflection.GeneratedProtocolMessageType('CourierRetrieveRequest', (_message.Message,), {
  'DESCRIPTOR' : _COURIERRETRIEVEREQUEST,
  '__module__' : 'logistics.protos.courier_proto.courier_pb2'
  # @@protoc_insertion_point(class_scope:courier.CourierRetrieveRequest)
  })
_sym_db.RegisterMessage(CourierRetrieveRequest)



_COURIERCONTROLLER = _descriptor.ServiceDescriptor(
  name='CourierController',
  full_name='courier.CourierController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=236,
  serialized_end=530,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='courier.CourierController.List',
    index=0,
    containing_service=None,
    input_type=_COURIERLISTREQUEST,
    output_type=_COURIER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='courier.CourierController.Create',
    index=1,
    containing_service=None,
    input_type=_COURIER,
    output_type=_COURIER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Retrieve',
    full_name='courier.CourierController.Retrieve',
    index=2,
    containing_service=None,
    input_type=_COURIERRETRIEVEREQUEST,
    output_type=_COURIER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Update',
    full_name='courier.CourierController.Update',
    index=3,
    containing_service=None,
    input_type=_COURIER,
    output_type=_COURIER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Destroy',
    full_name='courier.CourierController.Destroy',
    index=4,
    containing_service=None,
    input_type=_COURIER,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_COURIERCONTROLLER)

DESCRIPTOR.services_by_name['CourierController'] = _COURIERCONTROLLER

# @@protoc_insertion_point(module_scope)
