# Generated by Django 3.2.8 on 2022-02-09 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0004_companybrand_brand_key"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="companybrand",
            table="company_brands",
        ),
    ]
