# Generated by Django 3.2.8 on 2022-02-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0007_auto_20220210_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybrand',
            name='brand_keyname',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
