# Generated by Django 3.2.8 on 2022-02-10 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0008_alter_companybrand_brand_keyname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybrand',
            old_name='brand_keyname',
            new_name='keyname',
        ),
    ]
