# Generated by Django 3.2.8 on 2022-02-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0009_rename_brand_keyname_companybrand_keyname'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='keyname',
            field=models.CharField(db_index=True, default='SSF', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
