# Generated by Django 3.2.8 on 2022-02-10 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("office", "0010_company_keyname"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="api_user",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="auth.user"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apikey",
            name="channel",
            field=models.CharField(
                choices=[("SABANGNET", "Sabangnet"), ("ECMONITOR", "Ecmonitor")],
                default="SABANGNET",
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("COMPANY_USER", "Company User"),
                    ("COMPANY_API", "Company Api"),
                ],
                default="ADMIN",
                max_length=30,
            ),
        ),
    ]
