# Generated by Django 3.2.8 on 2022-02-14 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("office", "0012_auto_20220210_0742"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="office.company",
            ),
            preserve_default=False,
        ),
    ]
