# Generated by Django 3.2.7 on 2021-10-02 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPaymentAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("CARD_CANCEL", "Card Cancel"), ("CASH", "Cash")],
                        max_length=20,
                    ),
                ),
                ("order_id", models.CharField(db_index=True, max_length=24)),
                ("previous_balance", models.IntegerField()),
                ("amount", models.IntegerField()),
                ("resulting_balance", models.IntegerField()),
                ("pg_response", models.JSONField(null=True)),
                ("bank_account_info", models.CharField(max_length=100)),
                ("reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
