# Generated by Django 3.2.7 on 2021-10-07 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=24)),
                ('detail', models.TextField(null=True)),
                ('action_type', models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('MEMO_ADD', 'Memo Add'), ('MEMO_DELETE', 'Memo Delete'), ('PAYMENT_ADJUSTMENT', 'Payment Adjustment'), ('REFUND_UPDATE', 'Refund Update')], max_length=100)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=24)),
                ('status_from', models.CharField(choices=[('PAYMENT_FINISHED', 'Payment Finished'), ('PRODUCT_PREPARING', 'Product Preparing'), ('DELIVERY_PREPARING', 'Delivery Preparing'), ('DELIVERY_STARTED', 'Delivery Started'), ('DELIVERY_FINISHED', 'Delivery Finished'), ('CONFIRM_PAYMENT', 'Confirm Payment'), ('CANCEL_REQUESTED', 'Cancel Requested'), ('CANCEL_PENDING', 'Cancel Pending'), ('CANCEL_FINISHED', 'Cancel Finished')], max_length=100)),
                ('status_to', models.CharField(choices=[('PAYMENT_FINISHED', 'Payment Finished'), ('PRODUCT_PREPARING', 'Product Preparing'), ('DELIVERY_PREPARING', 'Delivery Preparing'), ('DELIVERY_STARTED', 'Delivery Started'), ('DELIVERY_FINISHED', 'Delivery Finished'), ('CONFIRM_PAYMENT', 'Confirm Payment'), ('CANCEL_REQUESTED', 'Cancel Requested'), ('CANCEL_PENDING', 'Cancel Pending'), ('CANCEL_FINISHED', 'Cancel Finished')], max_length=100)),
                ('delivery_tracking_number_from', models.CharField(max_length=100, null=True)),
                ('delivery_tracking_url_from', models.CharField(max_length=100, null=True)),
                ('delivery_tracking_number_to', models.CharField(max_length=100, null=True)),
                ('delivery_tracking_url_to', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tagger.orderactionlog')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPaymentAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CARD_CANCEL', 'Card Cancel'), ('CASH', 'Cash')], max_length=20)),
                ('order_id', models.CharField(db_index=True, max_length=24)),
                ('previous_balance', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('resulting_balance', models.IntegerField()),
                ('pg_response', models.JSONField(null=True)),
                ('bank_account_info', models.CharField(max_length=100, null=True)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=24)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderAlimtalkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=24)),
                ('alimtalk_type', models.CharField(choices=[('DELIVERY_STARTED', 'Delivery Started'), ('CANCEL_FINISHED', 'Cancel Finished')], max_length=100)),
                ('request_id', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tagger.orderactionlog')),
            ],
        ),
    ]
