# Generated by Django 3.2.8 on 2021-10-07 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRefundUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=24)),
                ('refund_delivery_price', models.IntegerField()),
                ('refund_price', models.IntegerField()),
                ('refund_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tagger.orderactionlog')),
            ],
        ),
    ]
