# Generated by Django 3.2.8 on 2021-11-03 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tagger', '0002_orderrefundupdatelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_id', models.CharField(max_length=50)),
                ('product_type', models.CharField(choices=[('NORMAL', 'Normal Product'), ('TIMEDEAL', 'Timedeal Product')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sourcing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_code', models.CharField(db_index=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('asignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReceivedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=50)),
                ('order_type', models.CharField(choices=[('NORMAL_ORDER', 'Normal Order'), ('TIMEDEAL_ORDER', 'Timedeal Order')], max_length=50)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('size', models.CharField(max_length=50)),
                ('product_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ASSGINED', 'Assgined'), ('REQUESTED', 'Requested'), ('RECEIVED', 'Received'), ('REQUEST_CANCELED', 'Request Canceled'), ('OUT_OF_STOCK', 'Out Of Stock'), ('FROM_INVENTORY', 'From Inventory')], default='CREATED', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tagger.inventory')),
                ('sourcing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tagger.sourcing')),
            ],
        ),
    ]
