# Generated by Django 3.2.8 on 2021-11-05 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0003_inventory_receiveditem_sourcing'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_from_order_url',
            field=models.CharField(default='EMPTY', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_name',
            field=models.CharField(default='EMTPY', max_length=100),
            preserve_default=False,
        ),
    ]
