# Generated by Django 3.2.7 on 2021-10-05 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0003_ordermemo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermemo',
            old_name='user',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='orderpaymentadjustment',
            old_name='user',
            new_name='admin',
        ),
    ]
