# Generated by Django 3.2.8 on 2021-11-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0004_auto_20211105_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_brand',
            field=models.CharField(default='EMPTY', max_length=30),
            preserve_default=False,
        ),
    ]
