# Generated by Django 3.2.8 on 2021-11-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0005_inventory_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiveditem',
            name='sourcing_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_from_order_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
