# Generated by Django 3.2.7 on 2021-10-05 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tagger', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=24)),
                ('action_type', models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('MEMO_ADD', 'Memo Add'), ('MEMO_DELETE', 'Memo Delete'), ('PAYMENT_ADJUSTMENT', 'Payment Adjustment'), ('REFUND_UPDATE', 'Refund Update')], max_length=100)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=24)),
                ('status_from', models.CharField(choices=[('PAYMENT_FINISHED', 'Payment Finished'), ('PRODUCT_PREPARING', 'Product Preparing'), ('DELIVERY_PREPARING', 'Delivery Preparing'), ('DELIVERY_STARTED', 'Delivery Started'), ('DELIVERY_FINISHED', 'Delivery Finished'), ('CONFIRM_PAYMENT', 'Confirm Payment'), ('CANCEL_REQUESTED', 'Cancel Requested'), ('CANCEL_PENDING', 'Cancel Pending'), ('CANCEL_FINISHED', 'Cancel Finished')], max_length=100)),
                ('status_to', models.CharField(choices=[('PAYMENT_FINISHED', 'Payment Finished'), ('PRODUCT_PREPARING', 'Product Preparing'), ('DELIVERY_PREPARING', 'Delivery Preparing'), ('DELIVERY_STARTED', 'Delivery Started'), ('DELIVERY_FINISHED', 'Delivery Finished'), ('CONFIRM_PAYMENT', 'Confirm Payment'), ('CANCEL_REQUESTED', 'Cancel Requested'), ('CANCEL_PENDING', 'Cancel Pending'), ('CANCEL_FINISHED', 'Cancel Finished')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tagger.orderactionlog')),
            ],
        ),
    ]
