# Generated by Django 3.2.7 on 2021-10-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0006_orderactionlog_orderstatuschangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatuschangelog',
            name='delivery_tracking_number_from',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderstatuschangelog',
            name='delivery_tracking_number_to',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderstatuschangelog',
            name='delivery_tracking_url_from',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderstatuschangelog',
            name='delivery_tracking_url_to',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
