# Generated by Django 3.2.7 on 2021-10-05 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0007_auto_20211005_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderAlimtalkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=24)),
                ('request_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tagger.orderactionlog')),
            ],
        ),
    ]
