# Generated by Django 3.2.7 on 2021-10-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0008_orderalimtalklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderalimtalklog',
            name='request_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
