# Generated by Django 3.2.8 on 2021-11-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0008_inventory_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('order_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('ordered_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
