# Generated by Django 3.2.8 on 2021-11-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0009_extendedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='out_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.CharField(choices=[('IN_STOCK', 'In Stock'), ('PROCESSING_NEEDED', 'Processing Needed'), ('SHIPPED', 'Shipped'), ('SHIPPING_PENDING', 'Shipping Pending')], max_length=30),
        ),
    ]
