# Generated by Django 3.2.7 on 2021-10-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0009_alter_orderalimtalklog_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderalimtalklog',
            name='alimtalk_type',
            field=models.CharField(choices=[('DELIVERY_STARTED', 'Delivery Started'), ('CANCEL_FINISHED', 'Cancel Finished')], default='DELIVERY_STARTED', max_length=100),
            preserve_default=False,
        ),
    ]
