# Generated by Django 3.2.7 on 2021-10-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0010_orderalimtalklog_alimtalk_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderactionlog',
            name='detail',
            field=models.TextField(null=True),
        ),
    ]
