# Generated by Django 3.2.8 on 2021-11-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0010_auto_20211111_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiveditem',
            old_name='assignee',
            new_name='processor',
        ),
        migrations.RenameField(
            model_name='sourcing',
            old_name='asignee',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='sourcing',
            old_name='box_code',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='receiveditem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='receiveditem',
            name='sourcing_code',
        ),
        migrations.AddField(
            model_name='receiveditem',
            name='brand_keyname',
            field=models.CharField(default='UNKNOWN', max_length=50),
            preserve_default=False,
        ),
    ]
