# Generated by Django 3.2.8 on 2021-11-15 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0011_auto_20211115_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiveditem',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('REQUESTED', 'Requested'), ('RECEIVED', 'Received'), ('REQUEST_CANCELED', 'Request Canceled'), ('OUT_OF_STOCK', 'Out Of Stock'), ('FROM_INVENTORY', 'From Inventory')], default='CREATED', max_length=30),
        ),
    ]
