# Generated by Django 3.2.8 on 2021-11-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0012_alter_receiveditem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiveditem',
            name='sourcing_code',
            field=models.CharField(db_index=True, default='UNKNOWN', max_length=10),
            preserve_default=False,
        ),
    ]
