# Generated by Django 3.2.8 on 2021-11-15 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0013_receiveditem_sourcing_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiveditem',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receiveditem',
            name='needs_processing',
            field=models.BooleanField(default=False),
        ),
    ]
