# Generated by Django 3.2.8 on 2021-11-15 03:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0014_auto_20211115_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiveditem',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
