# Generated by Django 3.2.8 on 2021-11-15 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0015_receiveditem_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiveditem',
            name='ordered',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 5, 13, 14, 811561)),
            preserve_default=False,
        ),
    ]
