# Generated by Django 3.2.8 on 2021-11-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0016_receiveditem_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiveditem',
            name='memo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
