# Generated by Django 3.2.8 on 2021-11-15 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0018_auto_20211115_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='product_from_order_url',
        ),
    ]
