# Generated by Django 3.2.8 on 2021-11-15 12:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0019_remove_inventory_product_from_order_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None),
        ),
    ]
