# Generated by Django 3.2.8 on 2021-11-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0021_extendedorderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedorderitem',
            name='product_code',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
