# Generated by Django 3.2.8 on 2021-11-16 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0022_alter_extendedorderitem_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippableOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eoi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tagger.extendedorderitem')),
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tagger.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='ShippableOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PARTIAL', 'Partial'), ('FULL', 'Full')], max_length=16)),
                ('eo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tagger.extendedorder')),
            ],
        ),
    ]
