# Generated by Django 3.2.8 on 2021-11-16 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0023_shippableorder_shippableorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippableorderitem',
            name='shippable_order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tagger.shippableorder'),
            preserve_default=False,
        ),
    ]
