# Generated by Django 3.2.8 on 2021-11-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0024_shippableorderitem_shippable_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippableorderitem',
            name='status',
            field=models.CharField(choices=[('UNSPECIFIED', 'Unspecified'), ('PARTIAL', 'Partial'), ('FULL', 'Full'), ('LOCKED', 'Locked'), ('SHIPPED', 'Shipped')], default='UNSPECIFIED', max_length=16),
        ),
        migrations.AlterField(
            model_name='shippableorder',
            name='status',
            field=models.CharField(choices=[('UNSPECIFIED', 'Unspecified'), ('PARTIAL', 'Partial'), ('FULL', 'Full'), ('LOCKED', 'Locked'), ('SHIPPED', 'Shipped')], default='UNSPECIFIED', max_length=16),
        ),
    ]
