# Generated by Django 3.2.8 on 2021-11-16 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0025_auto_20211116_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sweettracker_id', models.IntegerField()),
                ('tracking_url_base', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=13, unique=True)),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=5)),
                ('recipient_name', models.CharField(max_length=60)),
                ('recipient_mobile', models.CharField(max_length=60)),
                ('tracking_number', models.CharField(max_length=50)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('deliver_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tagger.courier')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('LOCKED', 'Locked'), ('SHIPPED', 'Shipped')], default='CREATED', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingNoticeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='tagger.inventory')),
            ],
        ),
        migrations.RemoveField(
            model_name='shippableorderitem',
            name='eoi',
        ),
        migrations.RemoveField(
            model_name='shippableorderitem',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='shippableorderitem',
            name='shippable_order',
        ),
        migrations.RenameField(
            model_name='extendedorderitem',
            old_name='eo',
            new_name='extended_order',
        ),
        migrations.DeleteModel(
            name='ShippableOrder',
        ),
        migrations.DeleteModel(
            name='ShippableOrderItem',
        ),
        migrations.AddField(
            model_name='shippingnoticeitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tagger.extendedorderitem'),
        ),
        migrations.AddField(
            model_name='shippingnoticeitem',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tagger.shippingnotice'),
        ),
        migrations.AddField(
            model_name='package',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tagger.shippingnotice'),
        ),
        migrations.AddField(
            model_name='package',
            name='shipping_notice_items',
            field=models.ManyToManyField(to='tagger.ShippingNoticeItem'),
        ),
    ]
