# Generated by Django 3.2.8 on 2021-11-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0026_auto_20211116_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingnotice',
            name='code',
            field=models.CharField(db_index=True, max_length=13, unique=True),
        ),
    ]
