# Generated by Django 3.2.8 on 2021-11-16 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0027_alter_shippingnotice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='sweettracker_id',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='shippingnoticeitem',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tagger.shippingnotice'),
        ),
    ]
