# Generated by Django 3.2.8 on 2021-11-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0028_auto_20211116_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SHIPPED', 'Shipped'), ('DELIVER_CONFIRMED', 'Deliver Confirmed')], default='CREATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='courier',
            name='tracking_url_base',
            field=models.TextField(blank=True, default='https://search.naver.com/search.naver?query='),
        ),
    ]
