# Generated by Django 3.2.8 on 2021-11-16 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0029_auto_20211116_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='tagger.shippingnotice'),
        ),
    ]
