# Generated by Django 3.2.8 on 2021-11-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0030_alter_package_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingnotice',
            name='sealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SEALED', 'Sealed'), ('SHIPPED', 'Shipped'), ('DELIVER_CONFIRMED', 'Deliver Confirmed')], default='CREATED', max_length=30),
        ),
        migrations.AlterField(
            model_name='shippingnotice',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('LOCKED', 'Locked'), ('SEALED', 'Sealed'), ('SHIPPED', 'Shipped')], default='CREATED', max_length=20),
        ),
    ]
