# Generated by Django 3.2.8 on 2021-11-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0031_auto_20211117_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='sealed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
