# Generated by Django 3.2.8 on 2021-11-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0032_package_sealed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingnotice',
            name='template_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
