# Generated by Django 3.2.8 on 2021-12-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0033_shippingnotice_template_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
