# Generated by Django 3.2.8 on 2022-01-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='alloff_order_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.CharField(db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_memo',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_items',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
    ]
