# Generated by Django 3.2.8 on 2022-01-20 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220120_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_fee', models.IntegerField()),
                ('refund_amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.order')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='order.orderitem')),
            ],
            options={
                'db_table': 'refund_items',
            },
        ),
        migrations.CreateModel(
            name='RefundItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_from', models.IntegerField(blank=True, null=True)),
                ('fee_from', models.IntegerField(blank=True, null=True)),
                ('amount_to', models.IntegerField()),
                ('fee_to', models.IntegerField()),
                ('refund_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='histories', to='order.refunditem')),
            ],
            options={
                'db_table': 'refund_item_histories',
            },
        ),
    ]
