# Generated by Django 3.2.8 on 2022-01-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_refunditem_refunditemhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='alloff_order_id',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order_item_code',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_id',
            field=models.CharField(db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='app_scheme',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='payment',
            name='buyer_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='buyer_mobile',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='payment',
            name='buyer_post_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='payment',
            name='company',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='imp_uid',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='merchant_uid',
            field=models.CharField(db_index=True, max_length=24),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay_method',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('PAYMENT_CREATED', 'Payment Created'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('PAYMENT_TIME_OUT', 'Payment Time Out'), ('PAYMENT_CANCELED', 'Payment Canceled'), ('PAYMENT_REFUND_REQUESTED', 'Payment Refund Requested'), ('PAYMENT_REFUND_FINISHED', 'Payment Refund Finished')], max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pg',
            field=models.CharField(max_length=32),
        ),
    ]
