# Generated by Django 3.2.8 on 2022-01-24 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20220123_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitemactionlog',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='orderitemmemo',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_img',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='tracking_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
