# Generated by Django 3.2.8 on 2022-01-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20220124_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='imp_uid',
            field=models.CharField(db_index=True, max_length=32, null=True),
        ),
    ]
