# Generated by Django 3.2.8 on 2022-01-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_payment_imp_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refunditem',
            name='refund_fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),

        migrations.RunSQL("alter table refund_items alter column refund_fee set default 0;"),
        migrations.RunSQL("alter table refund_items alter column refund_fee drop not null;"),
    ]
