# Generated by Django 3.2.8 on 2022-01-25 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0014_alter_orderitemactionlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemalimtalklog',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitemrefundupdatelog',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitemstatuschangelog',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitemactionlog',
            name='action_type',
            field=models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('MEMO_ADD', 'Memo Add'), ('MEMO_DELETE', 'Memo Delete'), ('PAYMENT_ADJUSTMENT', 'Payment Adjustment'), ('REFUND_UPDATE', 'Refund Update'), ('GENERATED_RECEIVED_ITEM', 'Generated Received Item'), ('FORCE_GENERATED_RECEIVED_ITEM', 'Force Generated Received Item'), ('RECEIVED_INVENTORY', 'Received Inventory')], db_index=True, max_length=100),
        ),
        migrations.CreateModel(
            name='ReceivedItemGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_force', models.BooleanField()),
                ('received_item_id', models.IntegerField(db_index=True)),
                ('received_item_code', models.CharField(db_index=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='received_item', to='order.orderitemactionlog')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.orderitem')),
            ],
            options={
                'db_table': 'received_item_generation_logs',
            },
        ),
        migrations.CreateModel(
            name='InventoryReceiptLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_item_id', models.IntegerField(db_index=True)),
                ('received_item_code', models.CharField(db_index=True, max_length=30)),
                ('inventory_id', models.IntegerField(db_index=True)),
                ('inventory_code', models.CharField(db_index=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='order.orderitemactionlog')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.orderitem')),
            ],
            options={
                'db_table': 'inventory_receipt_logs',
            },
        ),
    ]
