# Generated by Django 3.2.8 on 2022-01-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20220125_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='alloff_order_id',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
