# Generated by Django 3.2.8 on 2022-01-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_alloff_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_removed',
        ),
    ]
