# Generated by Django 3.2.8 on 2022-01-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_remove_orderitem_is_removed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
