name: Trigger Backoffice API Deployment

on:
  push:
    branches:
      - workflow-dispatch

jobs:
  deploy:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.PAT_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'lessbutter',
            repo: 'alloff-backoffice-api',
            workflow_id: 'version_minor.yml',
            ref: 'main'
          })
